title: High Impact Engineers
author: Last updated October 2025
description: "High Impact Engineers is a community of engineers who want to maximise their positive impact on the world."
baseurl: ""
url: "https://high-impact-engineers.github.io/"

theme: minima
plugins:
header_pages:
  - pages/community.md
  - pages/career.md
  - pages/causes.md
  - pages/podcast.md
  # - pages/bolohip.md
  - pages/contribute.md
  - pages/about.md
